### PR TITLE
all: add license to every module

### PR DESCRIPTION
**Pull request by Hiccup-C137**

### CODE REVIEW

**Review by AndersonQ — APPROVED** [review]

**Comment by AndersonQ** [comment]
@giulliano-bueno could you approve this PR? It's just updating the license to each individual go module to allow pkg.dev.go to display the documentation as per their [license policy](https://pkg.go.dev/license-policy).

**Comment by AndersonQ** [comment]
ping @giulliano-bueno, @mcrakhman, could you approve this PR? It's just updating the license to each individual go module to allow pkg.dev.go to display the documentation as per their [license policy](https://pkg.go.dev/license-policy).

**Review by giulliano-bueno — APPROVED** [review]

**Comment by giulliano-bueno** [comment]
> ping @giulliano-bueno, @mcrakhman, could you approve this PR? It's just updating the license to each individual go module to allow pkg.dev.go to display the documentation as per their [license policy](https://pkg.go.dev/license-policy).

I was talking with Lluis exactly about this problem this week. Thanks @Hiccup-C137

**Review by giulliano-bueno — CHANGES_REQUESTED** [review]
@Hiccup-C137 please fix Drone build. Thanks.

**Review by mcrakhman — APPROVED** [review]

**Pull request merged**
